import React, {
  useCallback,
  useEffect,
  useReducer,
  useState,
  useRef,
  useMemo,
} from "react";
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { motion } from "framer-motion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import {
  BookOpen,
  MessageCircle,
  Loader2,
  BrainCog,
  Scan,
  TestTube2,
  Code,
  GalleryVerticalEnd,
  Pencil,
} from "lucide-react";
import { useTranslation } from "react-i18next";
import { Input } from "@/components/ui/input";
import {
  getWorkSpace,
  getWorkSpaceChatHistory,
  sendWorkspaceChatMessage,
  generateWorkspaceAutoContext,
  getWorkspaceContexts,
} from "@/utils/_apis/learnPlayground-api";
import { useParams } from "react-router-dom";
import FlashCards from "../../../lib/flashcards/FlashCards";
import Tooltip from "@mui/material/Tooltip";
import ChatInput, {
  Context as ChatContext,
  Model as ChatModel,
} from "@/lib/chat/chatInput";
import ChatMessages from "@/lib/chat/ChatMessage";
import { initialState } from "@/lib/consts";
import MindMap from "@/lib/explantion/DeepExplnation";
import PdfReader from "@/lib/PdfReader";
import { QuizList } from "@/lib/quizzes/Quiz";
import { SummaryList } from "@/lib/summary/Summary";
import {
  ChatMessage,
  TabKey,
  Workspace,
  WorkspaceContext,
  WorkspaceContextInput,
} from "@/lib/types";
import YouTubeReader from "@/lib/YoutubeReader";
import {
  ChatSkeleton,
  ContentSkeleton,
  reducer,
  TabsSkeleton,
  getRateLimitToastMessage,
  isRateLimitError,
} from "../utils";
import { toast } from "sonner";
import { ScrollArea } from "@/components/ui/scroll-area";

const TABS_CONFIG = [
  { id: "chat", labelKey: "tabs.chat", icon: MessageCircle, isSoon: false },
  {
    id: "flashcards",
    labelKey: "tabs.flashcards",
    icon: GalleryVerticalEnd,
    isSoon: false,
  },
  { id: "quizzes", labelKey: "tabs.quizzes", icon: TestTube2, isSoon: false },
  { id: "summary", labelKey: "tabs.summary", icon: BookOpen, isSoon: false },
  {
    id: "deepExplanation",
    labelKey: "tabs.deepExplanation",
    icon: BrainCog,
    isSoon: false,
  },
  { id: "code", labelKey: "tabs.code", icon: Code, isSoon: true },
  { id: "note", labelKey: "tabs.notes", icon: Pencil, isSoon: true },
] as const;

const LearnPlayground: React.FC = () => {
  const { t, i18n } = useTranslation();
  const { id } = useParams();
  const [state, dispatch] = useReducer(reducer, initialState);
  const [workspaceLoading, setWorkspaceLoading] = useState(true);
  const [contentLoading, setContentLoading] = useState(false);
  const [workspace, setWorkspace] = useState<Workspace | undefined>();
  const [fullScreen, setFullScreen] = useState(false);
  const [workspaceContexts, setWorkspaceContexts] = useState<
    WorkspaceContext[]
  >([]);
  const [selectedContexts, setSelectedContexts] = useState<ChatContext[]>([]);
  const [autoContextEnabled, setAutoContextEnabled] = useState(false);
  const [autoContextLoading, setAutoContextLoading] = useState(false);
  const [appliedContextIds, setAppliedContextIds] = useState<string[]>([]);

  // Separate refs for fullscreen and split mode
  const fullscreenScrollRef = useRef<HTMLDivElement>(null);
  const splitScrollRef = useRef<HTMLDivElement>(null);

  // Separate states for fullscreen and split mode
  const [fullscreenScroll, setFullscreenScroll] = useState({
    canScrollLeft: false,
    canScrollRight: false,
    isDragging: false,
    startX: 0,
    scrollLeft: 0,
    velocity: 0,
    lastMoveTime: 0,
    lastX: 0,
  });

  const [splitScroll, setSplitScroll] = useState({
    canScrollLeft: false,
    canScrollRight: false,
    isDragging: false,
    startX: 0,
    scrollLeft: 0,
    velocity: 0,
    lastMoveTime: 0,
    lastX: 0,
  });

  const isRTL = i18n.dir() === "rtl";
  const [isResizing, setIsResizing] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  const autoContextCount = useMemo(() => {
    if (!workspaceContexts.length) return 0;
    const autoGenerated = workspaceContexts.filter(
      (ctx) => ctx.isAutoGenerated
    );
    return autoGenerated.length > 0
      ? autoGenerated.length
      : workspaceContexts.length;
  }, [workspaceContexts]);

  const mapContextType = useCallback((type?: string): ChatContext["type"] => {
    switch (type) {
      case "video":
        return "video";
      case "transcript":
        return "transcript";
      case "document":
        return "document";
      case "summary":
      case "ai_generated":
        return "summary";
      case "note":
      case "text":
        return "text";
      default:
        return "text";
    }
  }, []);

  const mapWorkspaceContextsToChat = useCallback(
    (contexts: WorkspaceContext[] = []): ChatContext[] =>
      contexts.map((context) => {
        const content = context.content ?? "";
        const rawTitle =
          (context.title ?? "").trim() ||
          (context.metadata?.title as string | undefined)?.trim() ||
          (context.metadata?.fileName as string | undefined)?.trim() ||
          (context.source ?? "").trim();
        const name =
          rawTitle && rawTitle.length > 0
            ? rawTitle
            : `Context ${(context.id || "").slice(0, 6) || ""}`;
        return {
          id: context.id,
          name,
          content,
          type: mapContextType(context.type),
          preview: content.length > 160 ? `${content.slice(0, 160)}…` : content,
          metadata: {
            ...context.metadata,
            source: context.source,
            isAutoGenerated: context.isAutoGenerated,
            workspaceContextId: context.id,
            scope: "workspace",
          },
        };
      }),
    [mapContextType]
  );

  const mapChatContextsToPayload = useCallback(
    (contexts: ChatContext[]): WorkspaceContextInput[] =>
      contexts
        .filter((ctx) => !(ctx.metadata?.fileId || ctx.file))
        .map((ctx) => ({
          id: ctx.id,
          title: ctx.name,
          content: ctx.content,
          type: ctx.type,
          source: ctx.metadata?.source,
          metadata: ctx.metadata,
        })),
    []
  );

  const getContextKey = useCallback((ctx: ChatContext): string => {
    return (
      ctx.id ||
      (ctx.metadata?.workspaceContextId as string | undefined) ||
      (ctx.metadata?.mentionToken as string | undefined) ||
      (ctx.metadata?.fileId as string | undefined) ||
      ctx.name
    );
  }, []);

  const availableContexts = useMemo(
    () => mapWorkspaceContextsToChat(workspaceContexts),
    [mapWorkspaceContextsToChat, workspaceContexts]
  );

  const handleContextsChange = useCallback(
    (contexts: ChatContext[]) => {
      setSelectedContexts(contexts);
      setAutoContextEnabled(false);
      const keys = contexts.map(getContextKey);
      setAppliedContextIds(keys);
    },
    [getContextKey]
  );

  useEffect(() => {
    if (!selectedContexts.length && autoContextEnabled) {
      setAutoContextEnabled(false);
    }
  }, [selectedContexts, autoContextEnabled]);

  useEffect(() => {
    setSelectedContexts((current) => {
      if (!current.length) return current;

      const attachmentContexts = current.filter(
        (ctx) => ctx.metadata?.fileId || ctx.file instanceof File
      );

      const selectedIds = new Set(
        current
          .filter((ctx) => ctx.metadata?.workspaceContextId)
          .map((ctx) => ctx.metadata?.workspaceContextId as string)
      );

      const updatedContexts = availableContexts.filter((ctx) =>
        ctx.metadata?.workspaceContextId
          ? selectedIds.has(ctx.metadata.workspaceContextId as string)
          : false
      );

      if (
        updatedContexts.length ===
          current.filter((ctx) => !ctx.metadata?.fileId && !ctx.file).length &&
        attachmentContexts.length ===
          current.filter((ctx) => ctx.metadata?.fileId || ctx.file).length
      ) {
        return current;
      }

      return [...updatedContexts, ...attachmentContexts];
    });
  }, [availableContexts]);

  const extractVideoId = useCallback((url: string): string | null => {
    if (url.includes("youtu.be/")) {
      return url.split("/").pop()?.split("?")[0] || null;
    }
    return url.split("v=")[1]?.split("&")[0] || null;
  }, []);

  const fetchWorkspace = useCallback(async () => {
    if (!id) {
      setWorkspaceLoading(false);
      return;
    }

    try {
      setWorkspaceLoading(true);
      setContentLoading(true);

      const [response, history] = await Promise.all([
        getWorkSpace(id),
        getWorkSpaceChatHistory(id),
      ]);

      const workspaceData = response.workspace;
      workspaceData.chatMessages = history;

      let contextsList = (workspaceData.contexts as WorkspaceContext[]) ?? [];

      if (!contextsList.length) {
        try {
          contextsList = await getWorkspaceContexts(id);
        } catch (contextError) {
          console.log({ contextError });
          console.error("Failed to load workspace contexts:", contextError);
        }
      }

      workspaceData.contexts = contextsList;
      setWorkspaceContexts(contextsList);

      dispatch({ type: "SET_WORKSPACE", workspace: workspaceData });
      setWorkspace(workspaceData);

      const videoUrl = workspaceData.video?.url;
      const documentUrl = workspaceData.document?.url;

      if (videoUrl) {
        setFullScreen(false);
        dispatch({ type: "SET_WORKSPACE_TYPE", workspaceType: "video" });
        dispatch({ type: "SET_SRC", src: videoUrl });

        const videoId = extractVideoId(videoUrl);
        if (videoId) {
          dispatch({ type: "SET_YOUTUBE_VIDEO", videoId });
        }
        if (workspaceData.video?.transcript) {
          dispatch({
            type: "SET_TRANSCRIPT",
            transcript: workspaceData.video.transcript,
          });
        }
      } else if (documentUrl) {
        setFullScreen(false);
        dispatch({ type: "SET_WORKSPACE_TYPE", workspaceType: "document" });
        dispatch({ type: "SET_SRC", src: documentUrl });
      } else {
        workspaceData.type = "chat";
        dispatch({ type: "SET_WORKSPACE_TYPE", workspaceType: "chat" });
        dispatch({ type: "SET_SRC", src: "" });
        setFullScreen(true);
        setContentLoading(false);
      }
    } catch (error) {
      console.error("Failed to fetch workspace:", error);
      dispatch({
        type: "SET_STATUS",
        status: { kind: "error", message: "Failed to load workspace" },
      });
    } finally {
      setWorkspaceLoading(false);
      setTimeout(() => setContentLoading(false), 1000);
    }
  }, [id]);

  useEffect(() => {
    fetchWorkspace();
  }, [fetchWorkspace]);

  const handleAutoContext = useCallback(async () => {
    if (!id) return;
    try {
      setAutoContextLoading(true);
      const contexts = await generateWorkspaceAutoContext(id, true);
      setWorkspaceContexts(contexts);
      setWorkspace((prev) =>
        prev ? { ...prev, contexts: contexts ?? [] } : prev
      );
      setSelectedContexts(mapWorkspaceContextsToChat(contexts));
      const keys = contexts
        .map((ctx) => ctx.id)
        .filter((value): value is string => Boolean(value));
      setAppliedContextIds(keys);
      setAutoContextEnabled(contexts.length > 0);

      if (contexts.length > 0) {
        toast.success(
          t(
            "chat.auto_context_success",
            "Workspace context updated successfully."
          )
        );
      } else {
        toast.info(
          t(
            "chat.auto_context_empty",
            "No context was generated for this workspace yet."
          )
        );
      }
    } catch (error) {
      console.error("Failed to generate auto context:", error);
      setAutoContextEnabled(false);
      setAppliedContextIds([]);
      if (isRateLimitError(error)) {
        toast.error(getRateLimitToastMessage(isRTL));
      } else {
        toast.error(
          t(
            "chat.auto_context_failed",
            "Unable to generate context for this workspace."
          )
        );
      }
    } finally {
      setAutoContextLoading(false);
    }
  }, [id, mapWorkspaceContextsToChat, t]);

  const handleSendMessage = useCallback(
    async (
      message: string,
      model?: ChatModel,
      contextsOverride?: ChatContext[]
    ) => {
      if (!message.trim() || !id) return;

      const contextsToSend =
        contextsOverride && contextsOverride.length
          ? contextsOverride
          : selectedContexts;

      const attachmentContexts = contextsToSend.filter(
        (ctx) => ctx.metadata?.fileId && ctx.file instanceof File
      );

      const attachmentFiles = attachmentContexts
        .map((ctx) => ctx.file)
        .filter((file): file is File => file instanceof File);

      const userAttachmentMetadata = attachmentContexts.map((ctx) => ({
        id:
          ctx.metadata?.fileId ??
          ctx.id ??
          `upload-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        filename: ctx.name,
        mimetype: ctx.file?.type,
        size: ctx.file?.size,
        type: ctx.type === "image" ? "image" : "text",
        status: "uploading",
      }));

      const contextPayload = mapChatContextsToPayload(contextsToSend);

      const userMessage: any = {
        id: Date.now().toString(),
        type: "user",
        role: "user",
        content: message.trim(),
        timestamp: new Date(),
        metadata:
          userAttachmentMetadata.length > 0
            ? { attachments: userAttachmentMetadata }
            : undefined,
      };

      dispatch({ type: "ADD_CHAT_MESSAGE", message: userMessage });
      dispatch({ type: "SET_CHAT_LOADING", loading: true });
      dispatch({ type: "SET_STREAMING_MESSAGE", content: "" });

      try {
        await sendWorkspaceChatMessage(
          id,
          message.trim(),
          i18n.language as "en" | "ar",
          {
            model: model?.id,
            contexts: contextPayload,
            autoContext: autoContextEnabled,
            attachments: attachmentFiles,
          },
          (chunk) => {
            if (Array.isArray(chunk.metadata?.attachments)) {
              const uploadedAttachments = chunk.metadata.attachments.map(
                (attachment: any) => ({
                  ...attachment,
                  status: "uploaded",
                })
              );
              dispatch({
                type: "UPDATE_MESSAGE_ATTACHMENTS",
                messageId: userMessage.id,
                attachments: uploadedAttachments,
              });
            }
            if (chunk.chunk) {
              dispatch({ type: "ADD_STREAMING_CHUNK", chunk: chunk.chunk });
            }
            if (chunk.isComplete) {
              dispatch({
                type: "COMPLETE_STREAMING_MESSAGE",
                content: chunk.chunk || "",
                metadata: chunk.metadata,
              });
            }
            if (
              chunk.isComplete &&
              Array.isArray(chunk.metadata?.contextsApplied)
            ) {
              const applied = (chunk.metadata.contextsApplied as any[])
                .map((item) => {
                  if (typeof item === "string") return item;
                  if (item && typeof item === "object") {
                    return (
                      (item.id as string | undefined) ||
                      (item.title as string | undefined) ||
                      ""
                    );
                  }
                  return "";
                })
                .filter((value): value is string => Boolean(value));
              if (applied.length) {
                setAppliedContextIds(applied);
              } else {
                setAppliedContextIds([]);
              }
              const hasWorkspaceApplied = (
                chunk.metadata.contextsApplied as any[]
              ).some(
                (item) =>
                  item && typeof item === "object" && item.scope === "workspace"
              );
              setAutoContextEnabled(hasWorkspaceApplied);
            }
            if (chunk.metadata?.error) {
              const errorMessage: ChatMessage = {
                id: Date.now().toString(),
                type: "assistant",
                content: chunk.metadata.error,
                timestamp: new Date(),
                metadata: { error: chunk.metadata.error },
              };
              dispatch({ type: "ADD_CHAT_MESSAGE", message: errorMessage });
              dispatch({ type: "SET_CHAT_LOADING", loading: false });
              dispatch({ type: "SET_STREAMING_MESSAGE", content: "" });
            }
          }
        );
      } catch (error) {
        console.error("Failed to send message:", error);
        if (userAttachmentMetadata.length > 0) {
          const failedAttachments = userAttachmentMetadata.map(
            (attachment) => ({
              ...attachment,
              status: "failed",
            })
          );
          dispatch({
            type: "UPDATE_MESSAGE_ATTACHMENTS",
            messageId: userMessage.id,
            attachments: failedAttachments,
          });
        }
        const hitLimit = isRateLimitError(error);
        const failureMessage = hitLimit
          ? getRateLimitToastMessage(isRTL)
          : t(
              "chat.error_occurred",
              "An error occurred while sending your message."
            );
        if (hitLimit) {
          toast.error(failureMessage);
        }
        const errorMessage: any = {
          id: Date.now().toString(),
          type: "assistant",
          role: "assistant",
          content: failureMessage,
          timestamp: new Date(),
          metadata: { error: failureMessage },
        };
        dispatch({ type: "ADD_CHAT_MESSAGE", message: errorMessage });
        dispatch({ type: "SET_CHAT_LOADING", loading: false });
        dispatch({ type: "SET_STREAMING_MESSAGE", content: "" });
        setAppliedContextIds([]);
      }
    },
    [
      id,
      i18n.language,
      mapChatContextsToPayload,
      selectedContexts,
      t,
      autoContextEnabled,
    ]
  );

  const handleQuickSend = useCallback(
    (message: string) =>
      handleSendMessage(message, undefined, selectedContexts),
    [handleSendMessage, selectedContexts]
  );

  // Fullscreen scroll functions
  const checkFullscreenScroll = useCallback(() => {
    if (fullscreenScrollRef.current) {
      const { scrollLeft, scrollWidth, clientWidth } =
        fullscreenScrollRef.current;
      const maxScroll = scrollWidth - clientWidth;
      setFullscreenScroll((prev) => ({
        ...prev,
        canScrollLeft: scrollLeft > 10,
        canScrollRight: scrollLeft < maxScroll - 10,
      }));
    }
  }, []);

  // Split mode scroll functions
  const checkSplitScroll = useCallback(() => {
    if (splitScrollRef.current) {
      const { scrollLeft, scrollWidth, clientWidth } = splitScrollRef.current;
      const maxScroll = scrollWidth - clientWidth;
      setSplitScroll((prev) => ({
        ...prev,
        canScrollLeft: scrollLeft > 10,
        canScrollRight: scrollLeft < maxScroll - 10,
      }));
    }
  }, []);

  // Setup scroll listeners for fullscreen
  useEffect(() => {
    if (!fullScreen) return;

    checkFullscreenScroll();
    const container = fullscreenScrollRef.current;
    if (!container) return;

    const handleScroll = () => checkFullscreenScroll();
    const handleResize = () => checkFullscreenScroll();

    container.addEventListener("scroll", handleScroll, { passive: true });
    window.addEventListener("resize", handleResize);

    const resizeObserver = new ResizeObserver(() => {
      checkFullscreenScroll();
    });

    if (container) {
      resizeObserver.observe(container);
    }

    const timeout = setTimeout(checkFullscreenScroll, 100);

    return () => {
      container.removeEventListener("scroll", handleScroll);
      window.removeEventListener("resize", handleResize);
      resizeObserver.disconnect();
      clearTimeout(timeout);
    };
  }, [checkFullscreenScroll, fullScreen, state.tab]);

  // Setup scroll listeners for split mode
  useEffect(() => {
    if (fullScreen) return;

    checkSplitScroll();
    const container = splitScrollRef.current;
    if (!container) return;

    const handleScroll = () => checkSplitScroll();
    const handleResize = () => checkSplitScroll();

    container.addEventListener("scroll", handleScroll, { passive: true });
    window.addEventListener("resize", handleResize);

    const resizeObserver = new ResizeObserver(() => {
      checkSplitScroll();
    });

    if (container) {
      resizeObserver.observe(container);
    }

    const timeout = setTimeout(checkSplitScroll, 100);

    return () => {
      container.removeEventListener("scroll", handleScroll);
      window.removeEventListener("resize", handleResize);
      resizeObserver.disconnect();
      clearTimeout(timeout);
    };
  }, [checkSplitScroll, fullScreen, state.tab]);

  // Fullscreen drag handlers with improved UX
  const handleFullscreenMouseDown = (e: React.MouseEvent) => {
    if (!fullscreenScrollRef.current) return;
    const container = fullscreenScrollRef.current;
    setFullscreenScroll((prev) => ({
      ...prev,
      isDragging: true,
      startX: e.clientX,
      scrollLeft: container.scrollLeft,
      velocity: 0,
      lastMoveTime: Date.now(),
      lastX: e.clientX,
    }));
  };

  const handleFullscreenMouseMove = (e: React.MouseEvent) => {
    if (!fullscreenScroll.isDragging || !fullscreenScrollRef.current) return;
    e.preventDefault();

    const container = fullscreenScrollRef.current;
    const now = Date.now();
    const deltaTime = now - fullscreenScroll.lastMoveTime;
    const deltaX = e.clientX - fullscreenScroll.lastX;

    // Calculate velocity for momentum
    const velocity = deltaTime > 0 ? deltaX / deltaTime : 0;

    // Smooth drag with higher sensitivity
    const walk = (fullscreenScroll.startX - e.clientX) * 1.2;
    container.scrollLeft = fullscreenScroll.scrollLeft + walk;

    setFullscreenScroll((prev) => ({
      ...prev,
      velocity,
      lastMoveTime: now,
      lastX: e.clientX,
    }));
  };

  const handleFullscreenMouseUp = () => {
    if (!fullscreenScrollRef.current) return;

    // Apply momentum scrolling
    const container = fullscreenScrollRef.current;
    let momentum = fullscreenScroll.velocity * -150; // Convert velocity to pixels
    const friction = 0.92; // Friction coefficient

    const animate = () => {
      if (Math.abs(momentum) < 0.5) return;

      momentum *= friction;
      container.scrollLeft += momentum;
      requestAnimationFrame(animate);
    };

    if (Math.abs(momentum) > 1) {
      requestAnimationFrame(animate);
    }

    setFullscreenScroll((prev) => ({
      ...prev,
      isDragging: false,
      velocity: 0,
    }));
  };

  const handleFullscreenTouchStart = (e: React.TouchEvent) => {
    if (!fullscreenScrollRef.current) return;
    const container = fullscreenScrollRef.current;
    setFullscreenScroll((prev) => ({
      ...prev,
      isDragging: true,
      startX: e.touches[0].clientX,
      scrollLeft: container.scrollLeft,
      velocity: 0,
      lastMoveTime: Date.now(),
      lastX: e.touches[0].clientX,
    }));
  };

  const handleFullscreenTouchMove = (e: React.TouchEvent) => {
    if (!fullscreenScroll.isDragging || !fullscreenScrollRef.current) return;

    const container = fullscreenScrollRef.current;
    const now = Date.now();
    const deltaTime = now - fullscreenScroll.lastMoveTime;
    const deltaX = e.touches[0].clientX - fullscreenScroll.lastX;

    const velocity = deltaTime > 0 ? deltaX / deltaTime : 0;

    const walk = (fullscreenScroll.startX - e.touches[0].clientX) * 1.2;
    container.scrollLeft = fullscreenScroll.scrollLeft + walk;

    setFullscreenScroll((prev) => ({
      ...prev,
      velocity,
      lastMoveTime: now,
      lastX: e.touches[0].clientX,
    }));
  };

  const handleFullscreenTouchEnd = () => {
    if (!fullscreenScrollRef.current) return;

    const container = fullscreenScrollRef.current;
    let momentum = fullscreenScroll.velocity * -150;
    const friction = 0.92;

    const animate = () => {
      if (Math.abs(momentum) < 0.5) return;

      momentum *= friction;
      container.scrollLeft += momentum;
      requestAnimationFrame(animate);
    };

    if (Math.abs(momentum) > 1) {
      requestAnimationFrame(animate);
    }

    setFullscreenScroll((prev) => ({
      ...prev,
      isDragging: false,
      velocity: 0,
    }));
  };

  // Split mode drag handlers with improved UX
  const handleSplitMouseDown = (e: React.MouseEvent) => {
    if (!splitScrollRef.current) return;
    const container = splitScrollRef.current;
    setSplitScroll((prev) => ({
      ...prev,
      isDragging: true,
      startX: e.clientX,
      scrollLeft: container.scrollLeft,
      velocity: 0,
      lastMoveTime: Date.now(),
      lastX: e.clientX,
    }));
  };

  const handleSplitMouseMove = (e: React.MouseEvent) => {
    if (!splitScroll.isDragging || !splitScrollRef.current) return;
    e.preventDefault();

    const container = splitScrollRef.current;
    const now = Date.now();
    const deltaTime = now - splitScroll.lastMoveTime;
    const deltaX = e.clientX - splitScroll.lastX;

    const velocity = deltaTime > 0 ? deltaX / deltaTime : 0;

    const walk = (splitScroll.startX - e.clientX) * 1.2;
    container.scrollLeft = splitScroll.scrollLeft + walk;

    setSplitScroll((prev) => ({
      ...prev,
      velocity,
      lastMoveTime: now,
      lastX: e.clientX,
    }));
  };

  const handleSplitMouseUp = () => {
    if (!splitScrollRef.current) return;

    const container = splitScrollRef.current;
    let momentum = splitScroll.velocity * -150;
    const friction = 0.92;

    const animate = () => {
      if (Math.abs(momentum) < 0.5) return;

      momentum *= friction;
      container.scrollLeft += momentum;
      requestAnimationFrame(animate);
    };

    if (Math.abs(momentum) > 1) {
      requestAnimationFrame(animate);
    }

    setSplitScroll((prev) => ({ ...prev, isDragging: false, velocity: 0 }));
  };

  const handleSplitTouchStart = (e: React.TouchEvent) => {
    if (!splitScrollRef.current) return;
    const container = splitScrollRef.current;
    setSplitScroll((prev) => ({
      ...prev,
      isDragging: true,
      startX: e.touches[0].clientX,
      scrollLeft: container.scrollLeft,
      velocity: 0,
      lastMoveTime: Date.now(),
      lastX: e.touches[0].clientX,
    }));
  };

  const handleSplitTouchMove = (e: React.TouchEvent) => {
    if (!splitScroll.isDragging || !splitScrollRef.current) return;

    const container = splitScrollRef.current;
    const now = Date.now();
    const deltaTime = now - splitScroll.lastMoveTime;
    const deltaX = e.touches[0].clientX - splitScroll.lastX;

    const velocity = deltaTime > 0 ? deltaX / deltaTime : 0;

    const walk = (splitScroll.startX - e.touches[0].clientX) * 1.2;
    container.scrollLeft = splitScroll.scrollLeft + walk;

    setSplitScroll((prev) => ({
      ...prev,
      velocity,
      lastMoveTime: now,
      lastX: e.touches[0].clientX,
    }));
  };

  const handleSplitTouchEnd = () => {
    if (!splitScrollRef.current) return;

    const container = splitScrollRef.current;
    let momentum = splitScroll.velocity * -150;
    const friction = 0.92;

    const animate = () => {
      if (Math.abs(momentum) < 0.5) return;

      momentum *= friction;
      container.scrollLeft += momentum;
      requestAnimationFrame(animate);
    };

    if (Math.abs(momentum) > 1) {
      requestAnimationFrame(animate);
    }

    setSplitScroll((prev) => ({ ...prev, isDragging: false, velocity: 0 }));
  };

  const getDisplayTitle = useCallback(() => {
    return (
      state.workspace?.workspaceName ||
      state.workspace?.title ||
      state.title ||
      "Untitled Workspace"
    );
  }, [state.workspace, state.title]);

  const renderContent = () => {
    if (contentLoading) {
      return <ContentSkeleton />;
    }

    if (state.type === "document") {
      return (
        <PdfReader
          src={state.src || ""}
          page={state.page}
          zoom={state.zoom}
          status={state.status}
          onLoaded={(pageCount) => {
            dispatch({ type: "SET_PAGE_COUNT", pageCount });
            dispatch({ type: "SET_STATUS", status: { kind: "idle" } });
            setContentLoading(false);
          }}
          onError={(message) => {
            dispatch({
              type: "SET_STATUS",
              status: { kind: "error", message },
            });
            setContentLoading(false);
          }}
          onGoto={(p) => dispatch({ type: "SET_PAGE", page: p })}
          onZoomIn={() => dispatch({ type: "ZOOM_IN" })}
          onZoomOut={() => dispatch({ type: "ZOOM_OUT" })}
          onResetZoom={() => dispatch({ type: "RESET_ZOOM" })}
          onTextSelect={(text) => dispatch({ type: "SET_SELECTED_TEXT", text })}
          onAddToChat={(text) => dispatch({ type: "ADD_TO_CHAT", text })}
          pageCount={state.pageCount}
        />
      );
    }

    if (state.type === "video") {
      return (
        <YouTubeReader
          videoId={state.youtubeVideoId || ""}
          transcript={state.workspace?.video?.transcript?.data as any}
          onVideoSelect={(videoId) =>
            dispatch({ type: "SET_YOUTUBE_VIDEO", videoId })
          }
          onTimeUpdate={(currentTime, duration) =>
            dispatch({ type: "SET_YOUTUBE_TIME", currentTime, duration })
          }
          onPlay={() =>
            dispatch({ type: "SET_YOUTUBE_PLAYING", isPlaying: true })
          }
          onPause={() =>
            dispatch({ type: "SET_YOUTUBE_PLAYING", isPlaying: false })
          }
          onReady={() => setContentLoading(false)}
          onTranscriptLoad={(transcript) =>
            dispatch({ type: "SET_TRANSCRIPT", transcript })
          }
          className="w-full h-full flex-grow"
        />
      );
    }

    return null;
  };

  if (workspaceLoading) {
    return (
      <section
        style={{
          maxHeight: "calc(100vh - 3rem)",
          minHeight: "calc(100vh - 3rem)",
        }}
        dir={isRTL ? "rtl" : "ltr"}
        className="flex items-center justify-center"
      >
        <div className="flex flex-col items-center space-y-4">
          <Loader2 className="h-8 w-8 animate-spin text-zinc-600 dark:text-zinc-400" />
          <p className="text-sm text-zinc-600 dark:text-zinc-300">
            {t("loading.workspace", "Loading workspace...")}
          </p>
        </div>
      </section>
    );
  }

  return (
    <section
      style={{ height: "calc(100vh)" }}
      dir={isRTL ? "rtl" : "ltr"}
      className="flex flex-col"
    >
      <div className="p-2 pb-0 pl-12 flex items-center justify-between flex-shrink-0">
        <div className="max-w-[34rem] flex-grow relative">
          {workspaceLoading ? (
            <Skeleton className="h-10 w-full rounded-2xl" />
          ) : (
            <Input
              className="rounded-2xl shadow-none border-none text-zinc-900 dark:text-zinc-100 w-full"
              value={getDisplayTitle()}
              readOnly
            />
          )}
          {contentLoading && (
            <div className="absolute right-3 top-1/2 transform -translate-y-1/2">
              <Loader2 className="h-4 w-4 animate-spin text-zinc-400 dark:text-zinc-500" />
            </div>
          )}
        </div>
      </div>

      <ResizablePanelGroup
        key={fullScreen ? "pg-full" : "pg-split"}
        direction="horizontal"
        dir="ltr"
        className="flex-1 min-h-0"
        autoSaveId={fullScreen ? "fs-layout" : "split-layout"}
      >
        {fullScreen ? (
          <ResizablePanel
            defaultSize={100}
            minSize={0}
            className="mt-2 min-h-0 flex flex-col"
          >
            <motion.div
              initial={{ x: 20, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              transition={{ type: "spring", stiffness: 260, damping: 30 }}
              className="h-full flex flex-col min-h-0 px-2 sm:px-6 mx-2 sm:mx-4"
            >
              {workspaceLoading ? (
                <TabsSkeleton />
              ) : (
                <Tabs
                  value={state.tab}
                  onValueChange={(v) =>
                    dispatch({ type: "SET_TAB", tab: v as TabKey })
                  }
                  className="h-full flex flex-col min-h-0"
                >
                  <div className="relative pb-4 flex-shrink-0 flex justify-center">
                    {fullscreenScroll.canScrollLeft && (
                      <>
                        <div
                          className="absolute left-0 top-0 bottom-4 w-24 z-30 pointer-events-none"
                          style={{
                            background:
                              "linear-gradient(to right, rgba(255, 255, 255, 0.95) 0%, rgba(255, 255, 255, 0) 100%)",
                          }}
                        />
                        <div
                          className="absolute left-0 top-0 bottom-4 w-24 z-30 pointer-events-none dark:block hidden"
                          style={{
                            background:
                              "linear-gradient(to right, rgba(9, 9, 11, 0.95) 0%, rgba(9, 9, 11, 0) 100%)",
                          }}
                        />
                      </>
                    )}

                    {fullscreenScroll.canScrollRight && (
                      <>
                        <div
                          className="absolute right-0 top-0 bottom-4 w-24 z-30 pointer-events-none"
                          style={{
                            background:
                              "linear-gradient(to left, rgba(255, 255, 255, 0.95) 0%, rgba(255, 255, 255, 0) 100%)",
                          }}
                        />
                        <div
                          className="absolute right-0 top-0 bottom-4 w-24 z-30 pointer-events-none dark:block hidden"
                          style={{
                            background:
                              "linear-gradient(to left, rgba(9, 9, 11, 0.95) 0%, rgba(9, 9, 11, 0) 100%)",
                          }}
                        />
                      </>
                    )}

                    <div
                      ref={fullscreenScrollRef}
                      className="overflow-x-scroll scrollbar-hide w-full select-none"
                      onMouseDown={handleFullscreenMouseDown}
                      onMouseMove={handleFullscreenMouseMove}
                      onMouseUp={handleFullscreenMouseUp}
                      onMouseLeave={handleFullscreenMouseUp}
                      onTouchStart={handleFullscreenTouchStart}
                      onTouchMove={handleFullscreenTouchMove}
                      onTouchEnd={handleFullscreenTouchEnd}
                      style={{
                        cursor: fullscreenScroll.isDragging
                          ? "grabbing"
                          : "grab",
                        userSelect: "none",
                        WebkitUserSelect: "none",
                        MozUserSelect: "none",
                        msUserSelect: "none",
                        overflowX: "scroll",
                        scrollbarWidth: "none",
                        msOverflowStyle: "none",
                        WebkitOverflowScrolling: "touch",
                      }}
                    >
                      <div className="flex items-center gap-3 w-max mx-auto">
                        <TabsList
                          className="relative !space-x-0 !p-1 sm:!p-1.5 flex items-center gap-1 sm:gap-2 h-10 sm:h-12 rounded-2xl border border-zinc-200/60 dark:border-zinc-800/60 bg-white/90
                 dark:bg-zinc-900/50 shadow-sm dark:shadow-zinc-950/20 backdrop-blur-md flex-shrink-0"
                          style={{ direction: isRTL ? "rtl" : "ltr" }}
                        >
                          {TABS_CONFIG.map((tab) => {
                            const IconComponent = tab.icon;
                            const isActive = state.tab === tab.id;
                            const isSoon = tab?.isSoon;

                            return (
                              <TabsTrigger
                                key={tab.id}
                                disabled={isSoon}
                                value={tab.id}
                                className={`px-2 sm:px-3 md:px-4 py-1.5 sm:py-2 relative z-20 flex-shrink-0 transition-all duration-200 
                hover:bg-zinc-50 dark:hover:bg-zinc-800/40 
                data-[state=active]:bg-zinc-100 dark:data-[state=active]:bg-zinc-800/60 
                rounded-lg sm:rounded-xl h-7 sm:h-9 flex flex-row items-center 
                justify-center select-none cursor-pointer gap-1 sm:gap-1.5 md:gap-2`}
                                onMouseDown={(e) => e.stopPropagation()}
                                onTouchStart={(e) => e.stopPropagation()}
                              >
                                {isActive ? (
                                  <div className="w-1 h-1 sm:w-1.5 sm:h-1.5 bg-emerald-500 rounded-full flex-shrink-0" />
                                ) : (
                                  <IconComponent className="size-3 sm:size-3.5 md:size-4 flex-shrink-0 text-zinc-600 dark:text-zinc-400" />
                                )}
                                <span
                                  className={`text-[10px] sm:text-xs md:text-sm font-medium transition-colors duration-200 whitespace-nowrap ${
                                    isActive
                                      ? "text-zinc-900 dark:text-zinc-100"
                                      : "text-zinc-700 dark:text-zinc-300"
                                  }`}
                                >
                                  {t(tab.labelKey as any)}
                                </span>
                              </TabsTrigger>
                            );
                          })}
                        </TabsList>

                        <Tooltip
                          title={t(
                            "workspace.exitFullScreen",
                            "Exit Full Screen"
                          )}
                          className="cursor-pointer flex-shrink-0"
                        >
                          <div
                            className="p-1.5 sm:p-2 rounded-xl hover:bg-zinc-100 dark:hover:bg-zinc-800/60 transition-colors duration-200"
                            onMouseDown={(e) => e.stopPropagation()}
                            onTouchStart={(e) => e.stopPropagation()}
                          >
                            <Scan
                              className="text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 transition-colors duration-200 size-4 sm:size-5"
                              onClick={() => {
                                setFullScreen(!fullScreen);
                              }}
                            />
                          </div>
                        </Tooltip>
                      </div>
                    </div>
                  </div>

                  <div className="flex-1 flex flex-col min-h-0">
                    {state.tab === "chat" && (
                      <TabsContent
                        value="chat"
                        className="m-0 flex-1 relative flex flex-col min-h-0"
                      >
                        {state.isLoading ? (
                          <div className="w-full flex-1">
                            <ChatSkeleton />
                          </div>
                        ) : (
                          <>
                            <ScrollArea>
                              <ChatMessages
                                messages={state.chatMessages || []}
                                isLoading={state.chatLoading}
                                streamingMessage={state.streamingMessage}
                                onSendMessage={handleQuickSend}
                              />
                            </ScrollArea>

                            <div className="absolute bottom-0 left-0 right-0 flex justify-center bg-gradient-to-t from-white dark:from-zinc-950 via-white/95 dark:via-zinc-950/95 to-transparent pt-4 pb-2 sm:pb-4">
                              <div className="w-full max-w-4xl px-2 sm:px-6">
                                <ChatInput
                                  className="w-full"
                                  value={state.prompt}
                                  hasAutoContext={true}
                                  expandSection={true}
                                  contexts={selectedContexts}
                                  availableContexts={availableContexts}
                                  autoContextCount={autoContextCount}
                                  autoContextLoading={autoContextLoading}
                                  onChange={(value: string) =>
                                    dispatch({
                                      type: "SET_PROMPT",
                                      prompt: value,
                                    })
                                  }
                                  onSubmit={(value, model, contexts) =>
                                    handleSendMessage(value, model, contexts)
                                  }
                                  onContextsChange={handleContextsChange}
                                  onAutoContextClick={handleAutoContext}
                                  appliedContextIds={appliedContextIds}
                                  placeholder={t(
                                    "chat.placeholder",
                                    `Ask anything about ${getDisplayTitle()}...`
                                  )}
                                />
                              </div>
                            </div>
                          </>
                        )}
                      </TabsContent>
                    )}

                    {state.tab === "flashcards" && workspace && (
                      <TabsContent
                        value="flashcards"
                        className="m-0 h-full w-full max-w-full"
                        style={{ maxHeight: "100%" }}
                      >
                        <FlashCards workspaceId={workspace.id} />
                      </TabsContent>
                    )}

                    {state.tab === "quizzes" && workspace && (
                      <TabsContent
                        value="quizzes"
                        className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 w-full max-w-full"
                      >
                        <QuizList
                          workspaceId={(workspace && workspace.id) || ""}
                        />
                      </TabsContent>
                    )}

                    {state.tab === "summary" && workspace?.id && (
                      <TabsContent
                        value="summary"
                        className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 w-full max-w-full"
                        style={{ maxHeight: "100%" }}
                      >
                        <SummaryList workspaceId={String(workspace.id)} />
                      </TabsContent>
                    )}

                    {state.tab === "deepExplanation" && (
                      <TabsContent
                        value="deepExplanation"
                        className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 flex flex-col w-full max-w-full"
                        style={{ maxHeight: "100%" }}
                      >
                        <MindMap
                          workspaceId={(workspace && workspace.id) || ""}
                        />
                      </TabsContent>
                    )}
                  </div>
                </Tabs>
              )}
            </motion.div>
          </ResizablePanel>
        ) : (
          <>
            <ResizablePanel
              defaultSize={50}
              minSize={30}
              className="mt-2 min-h-0 flex flex-col"
            >
              <motion.div
                initial={{ x: 20, opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                transition={{ type: "spring", stiffness: 260, damping: 30 }}
                className="h-full p-2 pt-0 flex flex-col min-h-0"
              >
                {renderContent()}
              </motion.div>
            </ResizablePanel>

            <ResizableHandle
              onPointerDown={() => setIsResizing(true)}
              onPointerUp={() => setIsResizing(false)}
              onPointerCancel={() => setIsResizing(false)}
              onMouseEnter={() => setIsHovered(true)}
              onMouseLeave={() => setIsHovered(false)}
              className="hover:bg-zinc-300 dark:hover:bg-zinc-700 transition-colors duration-200"
              style={{
                opacity: isResizing || isHovered ? 1 : 0,
                transition: "opacity 0.3s ease",
                cursor: "col-resize",
                pointerEvents: "auto",
              }}
            />

            <ResizablePanel
              defaultSize={50}
              minSize={30}
              className="mt-2 min-h-0 flex flex-col"
            >
              <motion.div
                initial={{ x: 20, opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                transition={{ type: "spring", stiffness: 260, damping: 30 }}
                className="h-full flex flex-col min-h-0"
              >
                {workspaceLoading ? (
                  <TabsSkeleton />
                ) : (
                  <Tabs
                    value={state.tab}
                    onValueChange={(v) =>
                      dispatch({ type: "SET_TAB", tab: v as TabKey })
                    }
                    className="h-full flex flex-col min-h-0"
                  >
                    <div className="relative p-2 pt-0 flex-shrink-0 flex justify-center">
                      {splitScroll.canScrollLeft && (
                        <>
                          {/* Light mode gradient */}
                          <div className="absolute left-2 top-0 bottom-0 w-20 z-30 pointer-events-none bg-gradient-to-r from-white/95 to-white/0 dark:hidden" />
                          {/* Dark mode gradient */}
                          <div className="absolute left-2 top-0 bottom-0 w-20 z-30 pointer-events-none hidden dark:block bg-gradient-to-r from-zinc-900/95 to-zinc-900/0" />
                        </>
                      )}

                      {splitScroll.canScrollRight && (
                        <>
                          {/* Light mode gradient */}
                          <div className="absolute right-2 top-0 bottom-0 w-20 z-30 pointer-events-none bg-gradient-to-l from-white/95 to-white/0 dark:hidden" />
                          {/* Dark mode gradient */}
                          <div className="absolute right-2 top-0 bottom-0 w-20 z-30 pointer-events-none hidden dark:block bg-gradient-to-l from-zinc-900/95 to-zinc-900/0" />
                        </>
                      )}

                      <div
                        ref={splitScrollRef}
                        className="overflow-x-scroll scrollbar-hide w-full select-none px-1"
                        onMouseDown={handleSplitMouseDown}
                        onMouseMove={handleSplitMouseMove}
                        onMouseUp={handleSplitMouseUp}
                        onMouseLeave={handleSplitMouseUp}
                        onTouchStart={handleSplitTouchStart}
                        onTouchMove={handleSplitTouchMove}
                        onTouchEnd={handleSplitTouchEnd}
                        style={{
                          cursor: splitScroll.isDragging ? "grabbing" : "grab",
                          userSelect: "none",
                          WebkitUserSelect: "none",
                          MozUserSelect: "none",
                          msUserSelect: "none",
                          overflowX: "scroll",
                          scrollbarWidth: "none",
                          msOverflowStyle: "none",
                          WebkitOverflowScrolling: "touch",
                        }}
                      >
                        <div className="flex items-center gap-2 w-max mx-auto">
                          <TabsList
                            className="relative !space-x-0 !p-0.5 sm:!p-1 flex items-center gap-0.5 sm:gap-1 md:gap-2 h-9 sm:h-10 md:h-11 rounded-xl sm:rounded-2xl border border-zinc-200/60 dark:border-zinc-800/60 bg-white/80 dark:bg-zinc-950/40 shadow-sm dark:shadow-none backdrop-blur-sm flex-shrink-0"
                            style={{ direction: isRTL ? "rtl" : "ltr" }}
                          >
                            {TABS_CONFIG.map((tab) => {
                              const IconComponent = tab.icon;
                              const isActive = state.tab === tab.id;
                              return (
                                <TabsTrigger
                                  key={tab.id}
                                  value={tab.id}
                                  disabled={tab.isSoon}
                                  className={`px-1.5 sm:px-2 md:px-3 py-1 sm:py-1.5 md:py-2 relative z-20 flex-shrink-0 transition-all duration-150 
                            hover:bg-transparent data-[state=active]:bg-zinc-100 dark:data-[state=active]:bg-zinc-800/60 rounded-lg sm:rounded-xl h-6 sm:h-7 md:h-9 flex flex-row items-center 
                            justify-center select-none cursor-pointer gap-1 sm:gap-1.5`}
                                  onMouseDown={(e) => e.stopPropagation()}
                                  onTouchStart={(e) => e.stopPropagation()}
                                >
                                  {isActive ? (
                                    <div className="w-1 h-1 sm:w-1.5 sm:h-1.5 bg-emerald-500 rounded-full flex-shrink-0" />
                                  ) : (
                                    <IconComponent className="size-3 sm:size-3.5 md:size-4 flex-shrink-0 text-zinc-600 dark:text-zinc-400" />
                                  )}
                                  <span
                                    className={`text-[10px] sm:text-xs md:text-sm font-normal transition-colors duration-150 whitespace-nowrap ${
                                      isActive
                                        ? "text-zinc-900 dark:text-zinc-100"
                                        : "text-zinc-700 dark:text-zinc-300"
                                    }`}
                                  >
                                    {t(tab.labelKey as any)}
                                  </span>
                                </TabsTrigger>
                              );
                            })}
                          </TabsList>

                          <Tooltip
                            title={t("workspace.fullScreen", "Full Screen")}
                            className="cursor-pointer flex-shrink-0"
                          >
                            <Scan
                              className="text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 transition-all ease-linear duration-200 size-4 sm:size-5"
                              onClick={() => {
                                setFullScreen(!fullScreen);
                              }}
                              onMouseDown={(e) => e.stopPropagation()}
                              onTouchStart={(e) => e.stopPropagation()}
                            />
                          </Tooltip>
                        </div>
                      </div>
                    </div>

                    <div className="flex-1 overflow-hidden flex flex-col min-h-0">
                      {state.tab === "chat" && (
                        <TabsContent
                          value="chat"
                          className="m-0 flex-1 flex flex-col relative items-stretch justify-end min-h-0 w-full max-w-full"
                        >
                          {state.isLoading ? (
                            <div className="w-full flex-1">
                              <ChatSkeleton />
                            </div>
                          ) : (
                            <>
                              <ScrollArea>
                                <ChatMessages
                                  messages={state.chatMessages || []}
                                  isLoading={state.chatLoading}
                                  streamingMessage={state.streamingMessage}
                                  onSendMessage={handleQuickSend}
                                />
                              </ScrollArea>
                              <ChatInput
                                className="flex-shrink-0 w-full p-5"
                                value={state.prompt}
                                hasAutoContext={true}
                                expandSection={true}
                                contexts={selectedContexts}
                                availableContexts={availableContexts}
                                autoContextCount={autoContextCount}
                                autoContextLoading={autoContextLoading}
                                onChange={(value: string) =>
                                  dispatch({
                                    type: "SET_PROMPT",
                                    prompt: value,
                                  })
                                }
                                onSubmit={(value, model, contexts) =>
                                  handleSendMessage(value, model, contexts)
                                }
                                onContextsChange={handleContextsChange}
                                onAutoContextClick={handleAutoContext}
                                appliedContextIds={appliedContextIds}
                                placeholder={t("aiActions.chatPlaceholder")}
                                optionsToHide={{
                                  models: true,
                                }}
                              />
                            </>
                          )}
                        </TabsContent>
                      )}

                      {state.tab === "flashcards" && workspace && (
                        <TabsContent
                          value="flashcards"
                          className="m-0 h-full flex flex-col w-full max-w-full"
                          style={{ maxHeight: "100%" }}
                        >
                          <FlashCards workspaceId={workspace.id} />
                        </TabsContent>
                      )}

                      {state.tab === "quizzes" && (
                        <TabsContent
                          value="quizzes"
                          className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 flex flex-col w-full max-w-full"
                        >
                          <QuizList
                            workspaceId={(workspace && workspace.id) || ""}
                          />
                        </TabsContent>
                      )}

                      {state.tab === "summary" && (
                        <TabsContent
                          value="summary"
                          className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 flex flex-col w-full max-w-full"
                          style={{ maxHeight: "100%" }}
                        >
                          <SummaryList
                            workspaceId={
                              String(workspace && workspace.id) || ""
                            }
                          />
                        </TabsContent>
                      )}

                      {state.tab === "deepExplanation" && (
                        <TabsContent
                          value="deepExplanation"
                          className="m-0 h-full p-4 text-zinc-500 dark:text-zinc-400 flex flex-col w-full max-w-full"
                          style={{ maxHeight: "100%" }}
                        >
                          <MindMap
                            workspaceId={(workspace && workspace.id) || ""}
                          />
                        </TabsContent>
                      )}
                    </div>
                  </Tabs>
                )}
              </motion.div>
            </ResizablePanel>
          </>
        )}
      </ResizablePanelGroup>
    </section>
  );
};

export default LearnPlayground;
